# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packed.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='packed.proto',
  package='lesson2',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cpacked.proto\x12\x07lesson2\"\x1c\n\nWordleDict\x12\x0e\n\x06letter\x18\x01 \x03(\x05\x62\x06proto3'
)




_WORDLEDICT = _descriptor.Descriptor(
  name='WordleDict',
  full_name='lesson2.WordleDict',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='letter', full_name='lesson2.WordleDict.letter', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=53,
)

DESCRIPTOR.message_types_by_name['WordleDict'] = _WORDLEDICT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WordleDict = _reflection.GeneratedProtocolMessageType('WordleDict', (_message.Message,), {
  'DESCRIPTOR' : _WORDLEDICT,
  '__module__' : 'packed_pb2'
  # @@protoc_insertion_point(class_scope:lesson2.WordleDict)
  })
_sym_db.RegisterMessage(WordleDict)


# @@protoc_insertion_point(module_scope)
