# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packed.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='packed.proto',
  package='lesson4',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cpacked.proto\x12\x07lesson4\"\x88\x01\n\nWordleTrie\x12-\n\x05nodes\x18\x01 \x03(\x0b\x32\x1e.lesson4.WordleTrie.WordleNode\x1aK\n\nWordleNode\x12\x0e\n\x06letter\x18\x01 \x01(\x05\x12-\n\x05nodes\x18\x02 \x03(\x0b\x32\x1e.lesson4.WordleTrie.WordleNodeb\x06proto3'
)




_WORDLETRIE_WORDLENODE = _descriptor.Descriptor(
  name='WordleNode',
  full_name='lesson4.WordleTrie.WordleNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='letter', full_name='lesson4.WordleTrie.WordleNode.letter', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='lesson4.WordleTrie.WordleNode.nodes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=162,
)

_WORDLETRIE = _descriptor.Descriptor(
  name='WordleTrie',
  full_name='lesson4.WordleTrie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='lesson4.WordleTrie.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_WORDLETRIE_WORDLENODE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=162,
)

_WORDLETRIE_WORDLENODE.fields_by_name['nodes'].message_type = _WORDLETRIE_WORDLENODE
_WORDLETRIE_WORDLENODE.containing_type = _WORDLETRIE
_WORDLETRIE.fields_by_name['nodes'].message_type = _WORDLETRIE_WORDLENODE
DESCRIPTOR.message_types_by_name['WordleTrie'] = _WORDLETRIE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WordleTrie = _reflection.GeneratedProtocolMessageType('WordleTrie', (_message.Message,), {

  'WordleNode' : _reflection.GeneratedProtocolMessageType('WordleNode', (_message.Message,), {
    'DESCRIPTOR' : _WORDLETRIE_WORDLENODE,
    '__module__' : 'packed_pb2'
    # @@protoc_insertion_point(class_scope:lesson4.WordleTrie.WordleNode)
    })
  ,
  'DESCRIPTOR' : _WORDLETRIE,
  '__module__' : 'packed_pb2'
  # @@protoc_insertion_point(class_scope:lesson4.WordleTrie)
  })
_sym_db.RegisterMessage(WordleTrie)
_sym_db.RegisterMessage(WordleTrie.WordleNode)


# @@protoc_insertion_point(module_scope)
